version: '3.1'

services:
  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html/

  db:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
